"""Structural checks on the Windows installer script.

The Inno Setup compiler only runs on Windows, so a mistake here is discovered
at the end of a release build, after every other platform has already been
built. That is the most expensive possible place to find a typo.

The first real release died on exactly that:

    Error on line 67 ... Column 1: 'BEGIN' expected.

Three comment lines. In an .iss file a semicolon starts a comment — but
[Code] is Pascal, where a semicolon ends a statement, so the compiler tried to
parse prose as code. These tests encode the rules the compiler enforces, and
run everywhere in under a second.
"""

import re
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parent.parent
ISS_PATH = APP_ROOT / "build-assets" / "receipts.iss"
ISS = ISS_PATH.read_text(encoding="utf-8")
LINES = ISS.splitlines()


def sections() -> dict:
    """Split the script into its [Section] blocks, keeping line numbers."""
    found, current = {}, None
    for lineno, line in enumerate(LINES, 1):
        header = re.match(r"^\[(\w+)\]\s*$", line.strip())
        if header:
            current = header.group(1)
            found.setdefault(current, [])
        elif current:
            found[current].append((lineno, line))
    return found


def test_code_section_uses_pascal_comments_only():
    """The exact failure from the v0.9.0 release build."""
    offenders = [
        f"receipts.iss:{lineno}: {line.strip()[:60]}"
        for lineno, line in sections().get("Code", [])
        if line.strip().startswith(";")
    ]
    assert not offenders, (
        "semicolon comments inside [Code] — that section is Pascal, so these "
        "are parsed as code and abort the compile. Use // instead, or move the "
        "note above [Code]:\n" + "\n".join(offenders)
    )


def test_non_code_sections_use_iss_comments():
    """The mirror image: // is not a comment outside [Code]."""
    offenders = []
    for name, lines in sections().items():
        if name == "Code":
            continue
        offenders += [
            f"receipts.iss:{lineno}: {line.strip()[:60]}"
            for lineno, line in lines
            if line.strip().startswith("//")
        ]
    assert not offenders, "// comments outside [Code]:\n" + "\n".join(offenders)


def test_pascal_blocks_are_balanced():
    code = "\n".join(line for _, line in sections().get("Code", []))
    stripped = re.sub(r"//.*", "", code)
    begins = len(re.findall(r"\bbegin\b", stripped, re.I))
    ends = len(re.findall(r"\bend\b", stripped, re.I))
    assert begins == ends, f"{begins} begin(s) but {ends} end(s) in [Code]"


def test_every_check_function_is_defined():
    """A Check: naming a function that does not exist fails at compile time."""
    referenced = set(re.findall(r"Check:\s*(\w+)", ISS))
    code = "\n".join(line for _, line in sections().get("Code", []))
    defined = set(re.findall(r"function\s+(\w+)", code, re.I))
    missing = referenced - defined
    assert not missing, f"Check: refers to undefined function(s): {sorted(missing)}"


def test_referenced_source_files_will_exist_at_compile_time():
    """Every Source: is either built by PyInstaller or fetched by the workflow."""
    release = (APP_ROOT / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    for source in re.findall(r'Source:\s*"([^"]+)"', ISS):
        name = source.split("\\")[-1]
        if source.startswith("..\\dist\\"):
            continue  # produced by the build step
        if name in release:
            continue  # downloaded or generated by the workflow
        assert (ISS_PATH.parent / source).exists(), (
            f"{source} is referenced by the installer but is not in the repo, "
            "not built, and not fetched by CI — ISCC would fail"
        )


def test_required_sections_are_present():
    present = set(sections())
    for required in ("Setup", "Files", "Icons", "Run"):
        assert required in present, f"[{required}] missing from the installer script"


def test_the_installer_does_not_require_administrator():
    """An admin prompt is one more scary dialog for someone trying a friend's app."""
    assert "PrivilegesRequired=lowest" in ISS


def test_the_output_filename_carries_the_version():
    assert "OutputBaseFilename=Receipts-Setup-{#AppVersion}" in ISS
    release = (APP_ROOT / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    assert "/DAppVersion=" in release, "CI never passes AppVersion; it would build as 0.0.0"
